spring:
  thymeleaf:
#    view-names: thymeleaf/* ## thymeleaf 로 시작하는 view 만 처리
#    prefix: classpath:templates/
#    suffix: .html
    cache: false

  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    hikari:
      minimum-idle: 1
      maximum-pool-size: 10
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
      auto-commit: true
      connection-test-query: SELECT 1

## mybatis java config 검토
mybatis:
  mapper-locations: mapper/**/*.xml
  type-aliases-package: kr.pe.inface.hub.service
  configuration:
    mapUnderscoreToCamelCase: true
    aggressiveLazyLoading: false
    lazyLoadingEnabled: true
    default-statement-timeout: 30
    default-fetch-size: 100


logging:
#  pattern:
#    console: "%highlight(## %d{HH:mm:ss.SSS} [%thread] %-5level %logger{20} %M{5}) - %msg %n"
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.jdbc.datasource.DataSourceTransactionManager: DEBUG
    org.springframework.web.servlet.DispatcherServlet: OFF
    org.springframework.web.servlet.handler.SimpleUrlHandlerMapping: OFF

    jdbc: OFF                  ### log4jdbc 옵션 설정 ###
    jdbc.connection: OFF       ### 커넥션 open close 이벤트를 로그로 남긴다. ###
    jdbc.sqlonly: OFF          ### SQL문만을 로그로 남기며, PreparedStatement일 경우 관련된 argument 값으로 대체된 SQL문이 보여진다. ###
    jdbc.sqltiming: DEBUG      ### SQL문과 해당 SQL을 실행시키는데 수행된 시간 정보(milliseconds)를 포함한다. ###
    jdbc.audit: OFF            ### ResultSet을 제외한 모든 JDBC 호출 정보를 로그로 남긴다. 많은 양의 로그가 생성되므로 특별히 JDBC 문제를 추적해야 할 필요가 있는 경우를 제외하고는 사용을 권장하지 않는다. ###
    jdbc.resultset: OFF        ### ResultSet을 포함한 모든 JDBC 호출 정보를 로그로 남기므로 매우 방대한 양의 로그가 생성된다. ###
    jdbc.resultsettable: DEBUG ### SQL 결과 조회된 데이터의 table을 로그로 남긴다. ###

    kr.pe.inface: DEBUG
    kr.pe.inface.hub.mapper: OFF ### mybatis mapper 로그 제외 처리


server:
  port: 80

  error:
    include-exception: true # 오류 응답에 exception의 내용을 포함할지 여부
    include-stacktrace: ALWAYS # [ALWAYS,NEVER,ON_PARAM,ON_TRACE_PARAM] 오류 응답에 stacktrace 내용을 포함할 지 여부

  servlet:
    encoding:
      charset: UTF-8
      enabled: true


# profile 별로 설정을 해야함..
# profile 별로 설정을 해야함..
# profile 별로 설정을 해야함..
# profile 별로 설정을 해야함..


# utf-8 셋팅
#
#logging:
#  level:
#    root: debug
#server:
#  port: 9090


#</configuration>
#spring:
#  application:
#    name: demo
#  profiles:
#    active: local
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: "jdbc:mysql://127.0.0.1:3306/jiniworld_test?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Seoul"
#    username: test
#    password: test
#    hikari:
#      auto-commit: false
#      connection-test-query: SELECT 1
#      minimum-idle: 10
#      maximum-pool-size: 50
#      transaction-isolation: TRANSACTION_READ_UNCOMMITTED
#      pool-name: pool-jiniworld
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    properties:
#      hibernate:
#        format_sql: true
#    generate-ddl: false
#    open-in-view: false
#  jackson:
#    serialization:
#      fail-on-empty-beans: false
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: Asia/Seoul
#  data:
#    rest:
#      default-page-size: 5
#      max-page-size: 20
#      detection-strategy: annotated # default
#      base-path: /api
#  security:
#    user:
#      name: admin
#      password: admin
#      roles:
#      - ADMIN
#      - VIEW
#  mvc:
#    static-path-pattern: /static/**
#  thymeleaf:
#    mode: HTML
#    encoding: UTF-8
#    check-template-location: true
#    prefix: classpath:/templates/
#    suffix: .html
#    cache: false
#  resources:
#    static-locations:
#    - classpath:/static/
#    cache:
#      period: 0
#server:
#  port: 8989
#  servlet:
#    context-path: /