spring:
  thymeleaf:
    #    view-names: thymeleaf/* ## thymeleaf 로 시작하는 view 만 처리
    prefix: classpath:/templates/
    #    suffix: .html
    cache: false
  devtools:
    livereload:
      enabled: true

  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url:  jdbc:log4jdbc:postgresql://192.168.0.25:5432/infacecbp
    username: inface
    password: inface
    hikari:
      minimum-idle: 1
      maximum-pool-size: 10
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
      auto-commit: true
      connection-test-query: SELECT 1

  servlet:
    multipart:
      #file-size-threshold: 1MB  ## 기준보다 작으면 임시스토리지에 저장하지 않고 메모리에서 생성.
      #location: C:/Temp         ## 기본값은 jvm 임시경로임
      max-file-size: 20MB         ## 파일 1개 제한
      max-request-size: 20MB     ## 요청 전체 제한


## mybatis java config 검토
mybatis:
  mapper-locations: mapper/**/*.xml
  type-aliases-package: com.inface.infaceCBP
  configuration:
    mapUnderscoreToCamelCase: true
    aggressiveLazyLoading: false
    lazyLoadingEnabled: true
    default-statement-timeout: 30
    default-fetch-size: 100


logging:
  #  pattern:
  #    console: "%highlight(## %d{HH:mm:ss.SSS} [%thread] %-5level %logger{20} %M{5}) - %msg %n"
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.jdbc.datasource.DataSourceTransactionManager: DEBUG
    org.springframework.web.servlet.DispatcherServlet: OFF
    org.springframework.web.servlet.handler.SimpleUrlHandlerMapping: OFF

    jdbc: OFF                  ### log4jdbc 옵션 설정 ###
    jdbc.connection: OFF       ### 커넥션 open close 이벤트를 로그로 남긴다. ###
    jdbc.sqlonly: OFF          ### SQL문만을 로그로 남기며, PreparedStatement일 경우 관련된 argument 값으로 대체된 SQL문이 보여진다. ###
    jdbc.sqltiming: DEBUG      ### SQL문과 해당 SQL을 실행시키는데 수행된 시간 정보(milliseconds)를 포함한다. ###
    jdbc.audit: OFF            ### ResultSet을 제외한 모든 JDBC 호출 정보를 로그로 남긴다. 많은 양의 로그가 생성되므로 특별히 JDBC 문제를 추적해야 할 필요가 있는 경우를 제외하고는 사용을 권장하지 않는다. ###
    jdbc.resultset: OFF        ### ResultSet을 포함한 모든 JDBC 호출 정보를 로그로 남기므로 매우 방대한 양의 로그가 생성된다. ###
    jdbc.resultsettable: DEBUG ### SQL 결과 조회된 데이터의 table을 로그로 남긴다. ###

    com.inface.infaceCBP: DEBUG
    com.inface.infaceCBP.mapper: OFF ### mybatis mapper 로그 제외 처리


server:
  port: 8190

  error:
    include-exception: true # 오류 응답에 exception의 내용을 포함할지 여부
    include-stacktrace: ALWAYS # [ALWAYS,NEVER,ON_PARAM,ON_TRACE_PARAM] 오류 응답에 stacktrace 내용을 포함할 지 여부

  servlet:
    encoding:
      charset: UTF-8
      enabled: true

# profile 별 설정파일 참고. local 설정은 default profile 로 설정. 이후 profile 지정에 의해 덮어쓰기됨. -Dspring.profiles.active=dev
# @ConfigurationProperties(prefix = "properties") 를 통해 pojo 에 매핑하는것도 가능(단, spEL 불가).  일단은 직접 @Value 사용하는 것으로.
# properties 설정


